"""New Migration

Revision ID: c0daee9ed380
Revises: 
Create Date: 2022-07-28 08:53:31.626943

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'c0daee9ed380'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('covid_data_sets',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('data_set_name', sa.String(), nullable=False),
    sa.Column('data_set_public_url', sa.String(), nullable=False),
    sa.Column('data_set_public_url_method', sa.String(), nullable=False),
    sa.Column('provider_long_name', sa.String(), nullable=False),
    sa.Column('provider_short_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('covid_cases_over_time_usa',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('date_stamp', sa.DateTime(), nullable=False),
    sa.Column('count_confirmed', sa.Integer(), nullable=False),
    sa.Column('count_death', sa.Integer(), nullable=False),
    sa.Column('count_recovered', sa.Integer(), nullable=False),
    sa.Column('covid_data_sets_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['covid_data_sets_id'], ['covid_data_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('covid_cases_over_time_usa')
    op.drop_table('covid_data_sets')
    # ### end Alembic commands ###
